#[derive(Debug)]
pub enum CommentType {
    Parenthesis,
    CurlyBrackets,
}

#[derive(Debug)]
pub enum Token {
    Identifier(String),
    Keyword(String),
    IntLiteral(String),
    FloatLiteral(String),
    CharLiteral(char),
    StringLiteral(String),
    AssignmentOperator,
    Operator(String),
    Symbol(String),
    Begin,
    End,
    StatementEnd,
    ProgramEnd,
    Comment(CommentType),
    Hash,
    Colon,
    Semicolon,
    PointerSymbol,
    DollarSign,
    AtSign,
    Ampersand,
    OpenParenthesis,
    CloseParenthesis,
    OpenSquareBracket,
    CloseSquareBracket,
    Period,
    Comma,
    Eof,
    Null,
}

pub static OPERATORS: &'static [char] = &[
    '+', '-', '*', '/', // Arithmetic operators
    '=', '<', '>', // Relational operators
];

pub static RESERVED_WORDS: &'static [&str] = &[
    "absolute",
    "and",
    "array",
    "asm",
    "begin",
    "break",
    "case",
    "const",
    "constructor",
    "continue",
    "destructor",
    "div",
    "do",
    "downto",
    "else",
    "end",
    "file",
    "for",
    "function",
    "goto",
    "if",
    "implementation",
    "in",
    "inherited",
    "inline",
    "interface",
    "label",
    "mod",
    "nil",
    "not",
    "object",
    "of",
    "on",
    "operator",
    "or",
    "packed",
    "procedure",
    "program",
    "record",
    "reintroduce",
    "repeat",
    "self",
    "set",
    "shl",
    "shr",
    "string",
    "then",
    "to",
    "type",
    "unit",
    "until",
    "uses",
    "var",
    "while",
    "with",
];

// Based on: https://wiki.freepascal.org/The_parser#Module_information
#[derive(Debug)]
pub struct Module {
    is_unit: bool,
    name: String,

    used_units: Vec<String>,
}
